name: Maven CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'OpenJDK'
        cache: maven
    - name: Package with maven
      run: mvn package
    - run: mkdir artifact && cp target/*.jar artifact
    - uses: actions/upload-artifact@v2
      with:
       name: Package
       path: artifact
